apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-selector
spec:
  type: NodePort
  selector:
    app: flask-app
    version: blue  # or green depending on your deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008  # Optional: specify a particular NodePort
